#!/usr/bin/env ruby
require 'shellwords'

def main
  loop do
    $stdout.print ENV['PROMPT']
    line = $stdin.gets.strip

    commands = line.scan( /([^"'|]+)|["']([^"']+)["']/ ).flatten.compact

    placeholder_in = $stdin
    placeholder_out = $stdout
    pipe = []

    commands.each_with_index do |command, index|
      program, *arguments = Shellwords.shellsplit(command)

      if BUILTINS.has_key?(program)
        BUILTINS[program].call(*arguments)

      else

        if index+1 < commands.size
          pipe = IO.pipe
          placeholder_out = pipe.last
        else
          placeholder_out = $stdout
        end

        pid = fork {
          unless placeholder_out == $stdout
            $stdout.reopen(placeholder_out)
            placeholder_out.close
          end

          unless placeholder_in == $stdin
            $stdin.reopen(placeholder_in)
            placeholder_in.close
          end

          exec program, *arguments
        }

        placeholder_out.close unless placeholder_out == $stdout
        placeholder_in.close unless placeholder_in == $stdin
        placeholder_in = pipe.first
      end
    end

    Process.waitall
  end
end

BUILTINS = {
  'cd' => lambda { |dir = ENV["HOME"]| Dir.chdir(dir) },
  'exit' => lambda { |code = 0| exit(code.to_i) },
  'exec' => lambda { |*command| exec *command },
  'set' => lambda { |args|
    key, value = args.split('=')
    ENV[key] = value
  }
}

ENV['PROMPT'] = '-> '

main

